---
name: "pre-release-macos11"

on:
  push:
    branches:
      - "release"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: macos-11

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.4.0"

      - run: "./scripts/setup.sh"
      - run: "./scripts/test.sh"
      - run: "./scripts/generate_exe.sh"
      - run: "ls dist/"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-macos11"
          prerelease: true
          title: "Development Build macOS 11"
          files: |
            dist/*
#            potemkeys/*.jsonc
        id: "automatic_releases_macos11"
